### PR TITLE
WIP: Fix javadoc generation

### PR DESCRIPTION
**Pull request by hinerm**
Fixes javadoc generation so that javadoc for all Fiji dependencies can be generated automatically.

### CODE REVIEW

**Comment by hinerm** [comment]
This is a TEMPORARY PR and is not intended to be merged yet! I created it to discuss the potential changes to fix http://jenkins.imagej.net/job/Fiji-javadoc/

**Comment by hinerm** [comment]
As far as I can tell, Javadoc for dependencies will NOT be generated for projects with a `packaging=pom` pom.xml.

Also, even with the `javadoc:jar` target configured to include dependency javadoc, manually invoking `javadoc:jar` will not grab dependency info - only when it is attached to part of the lifecycle, e.g. `package` phase, and the full lifecycle is executed.

Furthermore, `scope:runtime` dependencies are never included in javadoc generation.

This surely has to do with the how and when the classpath is generated. There may be other ways to get it to be correct when a `javadoc:*` goal is invoked, or to manually scrape the maven repo for the javadoc `.jar`s for all deps - but this is the simplest solution I could come up with to generate the javadoc automatically.

A more correct solution may be to use submodules and an actual aggregator pom... I'm not sure.

The biggest downside to this approach, I believe, is the non-pom-packaging and thus requirement of a source class. 

Another option might be to keep the pom-packaging in this project, but create another dedicated javadoc-aggregator project that is not meant for public consumption. Its pom.xml could be auto-generated from the fiji/fiji pom.xml by removing packaging and runtime scopes, and then manually deleting any javadoc for the dummy class before uploading it.

As a general note, we may want to restrict the included packages in the javadoc, e.g. to sc.fiji, net.imagej, org.scijava and io.scif.

Any thoughts @ctrueden ?

**Comment by ctrueden** [comment]
Do it the same way as imagej-javadoc?

Dedicated javadoc project gives much better (needed!) control.

**Comment by hinerm** [comment]
@ctrueden  yes indeed.. the [imagej-javadoc](https://github.com/imagej/imagej-javadoc) component is exactly how I think we should be generating javadoc for Fiji. Do you know of any reason not to do it this way..?

**Comment by hinerm** [comment]
Closing in favor of https://github.com/fiji/fiji-javadoc

**Pull request closed without merging**
