### PR TITLE
Added a new LUT called Random.lut

### PR DESCRIPTION
**Pull request by cmci**
Random.lut is a useful LUT for visualizing labeled objects with different colors in random order.

### CODE REVIEW

**Comment by cmci** [comment]
I could merge it by myself, but would wait for someone else to merge.

**Comment by ctrueden** [comment]
What about [Glasbey](http://imagej.net/Glasbey)? Doesn't that serve your purpose the same? It's what I use for labeled objects.

The fact that this new one is called "Random" might confuse users, who could expect that the lookup table will be dynamically and randomly generated, rather than a fixed set of random colors.

**Comment by tischi** [comment]
Glasbey is not bad, in fact I did not know about it! But I think:
1) mostly black background is much more intuitive
2) the name of the LUT should be more obvious

Could we have something like (with two options for the color of zero):
ColorLabelMaskBlack
ColorLabelMaskWhite

**Comment by cmci** [comment]
I did not know Glasbey as well ... It works well except for not being black background. How about 

**Galsbey** (as it is)
**GlasbeyBK** (new)

What do you think @ctrueden? @tischi?  If its OK, then I will change the color of pixel 0 of Glasbey to black and make a new pull request.

**Comment by ctrueden** [comment]
> If its OK, then I will change the color of pixel 0 of Glasbey to black and make a new pull request.

If you like. Another option would be to make "Glasbey (inverted)" as follows:
```javascript
run("glasbey");
run("RGB Color");
run("Invert");
run("8-bit Color", "number=256");
```
And then the first color index is black, of course.

**Comment by tischi** [comment]
@ctrueden I appreciate that this technically is a possibility but for daily use I find it too many lines of code. So I'd be for some LUT with 0=black by default.

**Comment by ctrueden** [comment]
@tischi I was not suggesting to use that macro for daily use. I was suggesting it to generate a new `Glasbey (inverted)` LUT which we would add to Fiji. What do you and @cmci think about that idea?

**Comment by tischi** [comment]
@ctrueden ok! sorry! sure! I just tried it and that would look very nice!

**Comment by cmci** [comment]
Good, then I will try work on it and amend the commit.

**Comment by ctrueden** [comment]
@cmci I went ahead and pushed it. Let me know if you see any issues with it!

**Pull request closed without merging**
