### PR TITLE
Add OMEVisual

### PR DESCRIPTION
**Pull request by hadim**
WIP. Need the pom-scijava PR to be merged first.

### CODE REVIEW

**Comment by hadim** [comment]
@ctrueden is this good to merge?

**Comment by ctrueden** [comment]
Please squash these two commits together into one, with pom-scijava 19.1.1 as the new parent version.

**Comment by ctrueden** [comment]
Actually, I changed my mind: I'll push the parent update now. So you can just rebase your single commit over the new master in a moment.

**Comment by ctrueden** [comment]
Ah ha, maintainer push rights. So nice. No need for you to do anything, @hadim. ^_^

**Comment by hadim** [comment]
Thanks!

**Pull request merged**
