### PR TITLE
Add a new upload-update-site.sh script

### PR DESCRIPTION
**Pull request by hadim**
@ctrueden Let me know what do you think.

### CODE REVIEW

**Comment by hadim** [comment]
ping @ctrueden

**Comment by ctrueden** [comment]
I hear your ping, @hadim! But I have zero bandwidth right now, sorry. Will try to study the implications of this, and hopefully merge, after some dust settles—maybe in January.

**Comment by ctrueden** [comment]
Ahh, I forgot all about this till I saw your new commit today.

Are you using this in production? And it's working well?

I'm nervous about deleting the old script. I need to check what (if anything) is currently using it.

Once again I'm in an extreme time crunch so I fear I cannot investigate before June 11. Please keep bugging me, so we can get this resolved soon.

**Comment by hadim** [comment]
It's ok since I can use it even if it's only this PR :-) Yes I use it in production for at least 3 projects:

- https://github.com/brouhardlab/Kappa
- https://github.com/hadim/Fiji_MaskRCNN
- https://github.com/hadim/FilamentDetector

**Comment by hadim** [comment]
According to https://github.com/search?p=3&q=upload-update-site.sh&type=Code it seems safe to repove the old one.

**Comment by ctrueden** [comment]
@hadim I agree that nothing in the SCM repositories for known downstream projects seems to reference it. However, there may be external build tools (e.g. Jenkins) out there still using it.

@sbesson @kennethgillen Do you know if Bio-Formats still uses Fiji's `upload-update-site.sh` script to populate the [Bio-Formats update site](https://sites.imagej.net/Bio-Formats)? It would be helpful to get confirmation either way before we merge this PR.

**Comment by sbesson** [comment]
@ctrueden the Bio-Formats site is now updated via https://github.com/ome/bio-formats-fiji and Travis CI and is completely independent of `upload-update-site.sh`. The logic of the script was copied from http://imagej.net/Automatic_Update_Site_Uploads#Automatic_Uploads_via_Travis_CI and largely matches the changes proposed by @hadim here. No objection to getting this merged from our side and thanks for checking.

**Comment by ctrueden** [comment]
Thanks @sbesson for reminding me, and for confirming that the merge here is OK!

**Pull request merged**
