### PR TITLE
Add "Glasbey On Black" LUT variant.

### PR DESCRIPTION
**Pull request by ehrenfeu**
The motivation for creating another Glasbey LUT variant was the fact that the
existing one with a dark background ("glasbey inverted") is having many colors
close to black, which makes them hard to perceive on the dark background - this
version is trying to avoid that.

It was created using the [Glasbey Python generator][1] by running the following
command:

```
echo "0,0,0" > black.txt
./glasbey.py --base-palette black.txt --no-black 256 glasbey-new_black-bg.txt
```

[1]: https://github.com/taketwo/glasbey

### CODE REVIEW

**Comment by imagejan** [comment]
@ehrenfeu for some reason, the link in your PR comment got wrong. The commit message contains the [correct link](https://github.com/taketwo/glasbey) though.
Thanks for pointing to this nice glasbey generator!

**Comment by ehrenfeu** [comment]
Thanks, @imagejan - fixed it...

**Comment by ctrueden** [comment]
@ehrenfeu Thanks.

Do you think it would make sense, in general, to add a Glasbey command which generates LUTs in a more flexible way? Then we wouldn't need to keep adding different Glasbey variants. What do you think?

**Comment by ehrenfeu** [comment]
@ctrueden sounds like a good idea! However, if I remember correctly (it has been a while already since I created the LUT), this involves some serious computation (order of several minutes) to generate the palette. That's probably kind of a show-stopper for integrating it as a command, no?
I'll check again and report back...

**Comment by imagejan** [comment]
A "generatable" LUT wouldn't need to adhere to the strict constraints (largest possible color distance between neighboring values) of the Glasbey LUT.
Something like the "Randomize Label Colors" function in KNIME/KNIP's Image Viewer (see [`RandomMissingColorHandler`](https://github.com/knime-ip/knip/blob/master/org.knime.knip.core/src/org/knime/knip/core/awt/labelingcolortable/RandomMissingColorHandler.java)) might still be helpful and sufficient.

**Comment by ehrenfeu** [comment]
That sounds nice, indeed!

**Pull request merged**
