### PR TITLE
Add methods

### PR DESCRIPTION
**Pull request by camlloyd**

### CODE REVIEW

**Comment by ctrueden** [comment]
@camlloyd Sorry I didn't get to reviewing this, but I've been insanely busy... did you close due to lack of response? If so, let's discuss. Or if you thought better of it, that's fine. Just let me know.

**Comment by camlloyd** [comment]
@ctrueden Hello Curtis, not a problem. I closed the PR as I wanted to review/update the file on my fork and felt the commit was a bit too soon. I'm keen to try and fill in some of the gaps here and so have created a separate repository for the JRuby library and would be most interested discussing it with you. I'm glad to hear from you, as I was starting to wonder whether I had contributed to something deprecated!

**Comment by ctrueden** [comment]
@camlloyd Sounds good, I await your updated PR then! And in the meantime, please ask on one of the [public channels](http://imagej.net/Communication) if you have any questions!

**Comment by camlloyd** [comment]
@ctrueden Thank you. I have submitted a new PR, I figured little and often is better. 

If it looks alright, I will continue...

**Pull request closed without merging**
