### PR TITLE
Add missing import

### PR DESCRIPTION
**Pull request by imagejan**
I also noticed that the file currently served by the Fiji update site seems to be an outdated version compared to the current master branch of this repo.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks!

**Comment by ctrueden** [comment]
Where should I upload the latest version? Is it safe to upload to the Fiji update site? Or should I upload it only to the Java-8 update site?

**Comment by imagejan** [comment]
Sorry, I didn't test with Java 6. Looking at the script, it should be fine, but I think TrakEM2 targets Java 8 now anyways (?).
I fear that this script anyways doesn't have a lot of users, as this issue wasn't discovered before and I also just stumbled upon it accidentally.
Uploading just to Java-8 should be fine.

Agreed on the point with versioned repositories, also that now we can use the SciJava script detection inside jars :)

**Comment by ctrueden** [comment]
This new version has now been uploaded to the Java-8 site.

**Pull request merged**
