### PR TITLE
Matplotlib LUTS

### PR DESCRIPTION
**Pull request by tferr**
Lots of [work](https://www.youtube.com/embed/xAoljeRJ3lU) went into the new Matplotlib [color maps](http://bids.github.io/colormap/) [(source)](https://github.com/BIDS/colormap/blob/master/colormaps.py). These are optimized to be perceptually-uniform when rendered both in color and in grayscale and are color-blind friendly. They are already available in R and Matlab and it would be great to have them also in IJ.

- Commit @33624bbb8aa9b2966f4f282721b99fb508384205 adds the four new LUTs: _inferno_, _magma_, _plasma_ and _viridis_ (the new matplotlib default)

-  Commit @9269589d3d78fa085f28261455f4b59cea2b6903 updates the documentation of the README file in the luts directory

A couple of things:

- I've kept `mpl-`in the filename so that we can remember what they are while navigating the _Image>Lookup Tables>_ menu, but perhaps is not suitable?
- I also wanted to include the new Matlab's default: the [parula LUT](http://blogs.mathworks.com/steve/2014/10/13/a-new-colormap-for-matlab-part-1-introduction/) (named after a [north-american bird](https://en.wikipedia.org/wiki/Parula)), but judging from this [comment](http://blogs.mathworks.com/steve/2014/10/20/a-new-colormap-for-matlab-part-2-troubles-with-rainbows/#comment-27702), it seems that MathWorks would consider a copyright infringement, so I left it out. To me, a possible replacement could be be _YlGnBu_r_ also used by Matplotlib ([original source](https://github.com/aschn/gnuplot-colorbrewer/blob/master/sequential/YlGnBu.plt)), although it is not exactly the same. If there is interest I could add it here.

### CODE REVIEW

**Comment by ctrueden** [comment]
Great, thank you. Sorry for the delay in review.

**Comment by ctrueden** [comment]
Also, I agree that it was best to leave out parula. Clearly a no-go, copyright-wise. (It would violate the rule of thumb: "Are you likely to get sued for using it?")

**Comment by imagejan** [comment]
AFAICT, this was merged but not uploaded to the Fiji update site yet. Would someone (@ctrueden? sorry to bother you..) take care of it?

**Comment by ctrueden** [comment]
@imagejan Uploaded.

**Pull request merged**
