### PR TITLE
 copytoImagePlus.m scripts

### PR DESCRIPTION
**Pull request by kouichi-c-nakamura**
MATLAB function `copytoImagePlus` is similar to `copytoImgPlus`, but instead of `ImgPlus` object of ImageJ2, it returns `ImagePlus` of ImageJ1. It supports up to 5D image data including hyperstack.

Test code etc is available below:
https://github.com/kouichi-c-nakamura/copytoImagePlus

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks. I'm going to merge it as-is for the moment, since it is useful.

In coming months, we should migrate all the MATLAB code out of this repository and into imagej/imagej-matlab instead.

**Comment by kouichi-c-nakamura** [comment]
Thanks. I think it'a good move, and we really need test code for them. At the moment they are so vulnerable to changes.

**Comment by ctrueden** [comment]
@kouichi-c-nakamura I agree! But I am not sure how to test them because we cannot install MATLAB on the cloud CI system, for licensing reasons. Do you have any suggestions?

**Comment by kouichi-c-nakamura** [comment]
No, no idea. I don't even know what CI system might be. Even if we can't run the tests automatically, I think it's better to have test code. Someone can run those code locally and manually and report problems, right?

**Comment by ctrueden** [comment]
The most promising candidate I could find is [here](https://github.com/scottclowe/matlab-continuous-integration). It uses the [MOxUnit](https://github.com/MOxUnit/MOxUnit) unit test package to run the unit tests via GNU Octave. This will of course impose some restrictions on the sorts of operations that can be tested, but would be worth a shot to get working.

Unfortunately I still have no bandwidth to work on any MATLAB stuff. But you are warmly welcome to check it out if you have time and interest.

**Comment by kouichi-c-nakamura** [comment]
Yeah, it sounds like a solution, but the compatibility between Octave and MATLAB aren't that great. Many newly added MATLAB functions won't run in Octave, I suppose?

I can see two choices:

1. To write MATLAB code strictly Octave-save way. I'm not sure if this is always possible.
2. Deploy full MATLAB unit tests to be run manually

If someone opts for free software, python may be a better friend. So I'm rather in favour of the latter, but this can be only because I have access to MATLAB now.

**Pull request merged**
