### PR TITLE
Correct 3d drift

### PR DESCRIPTION
**Pull request by tischi**
Fixed wrong Hyperstack assignments

### CODE REVIEW

**Comment by imagejan** [comment]
Your PR has conflicts with `fiji:master`. Can you pull all commits from `fiji:master` into your `tischi:master` first, and then rebase your changes on that?

**Comment by tischi** [comment]
I tried to follow exactly this recipe: http://imagej.net/How_to_contribute_to_an_existing_plugin_or_library
And I was hoping that those lines would do the trick in terms of having the latest fiji:master as the base:
```
$ cd fiji
$ git remote add upstream https://github.com/fiji/fiji
$ git fetch upstream
```
How do I have to do it differently?

**Comment by ctrueden** [comment]
FYI, I did create a new repository: https://github.com/fiji/Correct_3D_Drift

But did not have time to populate it yet with the history of this script. I was planning to do that, and turn over custody to you @tischi, which would alleviate some of these difficulties in the future.

I will try to complete that work later this month.

**Comment by tischi** [comment]
@ctrueden: Great! Thanks a lot! I think it is probably cleaner and easier if l wait for this! Thanks a lot again!

**Comment by ctrueden** [comment]
Status update: I did the Git history extraction for Correct_3D_Drift, but am polishing some POM-related stuff before I push it. Hopefully later today, or at least within a couple more days.

**Comment by ctrueden** [comment]
Finally, I pushed the new repo: https://github.com/fiji/Correct_3D_Drift.

If you could please reapply these changes on top of that latest version of the script, I'd appreciate it.

Also, let me know what level of maintenance you'd like to pledge toward maintaining this script. Please see [this list of roles](http://imagej.net/Team).

**Comment by tischi** [comment]
Hi Curtis,

Thanks! For this specific repo I could take over all the roles but Founder,
as I did not do the initial development.

Cheers, Tischi


_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Comment by ctrueden** [comment]
> For this specific repo I could take over all the roles but Founder,
> as I did not do the initial development.

Great! I updated the POM accordingly; see fiji/Correct_3D_Drift@58a9befed4c39458ef21b3eb2a5eed28b2ce43d9.

**Comment by tischi** [comment]
ok!
I updated the script


_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Comment by ctrueden** [comment]
Thanks @tischi. I have done the following things:

* Released `Correct_3D_Drift` version `1.0.0` [to the ImageJ Maven repository](http://maven.imagej.net/#nexus-search;gav~~Correct_3D_Drift~1.0.0~~)
* Uploaded it to the Java-8 update site
* [Added it to pom-scijava](https://github.com/scijava/pom-scijava/commit/ddebcf8da09790a706c290d1796093dc2a9d0336)
* [Added it to fiji](https://github.com/fiji/fiji/commit/b09ad4bfa8e20b53aa3d020d72e9f9c01a5cb96c)
* [Added it to fiji-javadoc](https://github.com/fiji/fiji-javadoc/commit/c39f575c81d001ae663d4f26f156e8eb628124cd)
* Removed the old bare `Correct_3D_drift.py` script from the Fiji and Java-8 update sites. (Unfortunately, this means that anyone using the Java 6 version of Fiji can no longer use this script, but due to a limitation in the updater, it is not possible to remove it from the Java-8 update site only such that Java 8 users no longer receive the bare script.)

So your latest version is now deployed to all people with up-to-date Fiji installations.

I am now done commenting on this obsolete GitHub thread. 😄  Further questions and issues should be raised either on the [ImageJ Forum](http://forum.imagej.net/) or as [issues in the Correct_3D_Drift repository](https://github.com/fiji/Correct_3D_Drift/issues).

**Comment by tischi** [comment]
ok! this is great! thank you very much!
one more question:
how is it about the update of this site: http://imagej.net/Correct_3D_drift
is this the official help site?
if so, should I have editing rights?



_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Comment by ctrueden** [comment]
> how is it about the update of this site: http://imagej.net/Correct_3D_drift
> is this the official help site?

Yes. I changed it so the D is capitalized.

> if so, should I have editing rights?

Yes, you already have full edit rights to everyone on the imagej.net wiki. I encourage you to edit boldly and often. It is very helpful.

**Comment by tischi** [comment]
ok. cool!

_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Pull request closed without merging**
