### PR TITLE
Fixed LUT listing

### PR DESCRIPTION
**Pull request by mutterer**
replaced eval'ed script that didn't work by the now builtin getList("LUTs") macro function

### CODE REVIEW

**Comment by imagejan** [comment]
@ctrueden as this change has been submitted in similar form by @lacan (#261) and @jdmanton (#264) as well, I think it can be considered well-tested and good to be merged, no?

**Comment by ctrueden** [comment]
@muttered Thanks! And sorry for the delay in merge. I had missed this till @imagejan's ping.

**Comment by miura** [comment]
Hi @mutterer @ctrueden @lacan @imagejan ,
Thanks a lot! We just now recognized this bug in a course. Will this change be automatically handled by the Updater (Help > Update...)? Currently, it is not and we fixed the local file manually. 
Kota

**Comment by manerotoni** [comment]
Hello,
the scripts shipped in the a recent and updated Fiji release (2021, 2022) is not the fixed script. 

Thanks

**Comment by DaniBodor** [comment]
I second that it would be nice to have this fixed in Fiji updates.

As a workaround, I have now added this function to some of my macros that use temporal color code to make sure it's fixed for all users. This might be useful for some others as well.

```
function fixTemporalColorCode(){
	// fixes a bug in the Temporal Color Code plugin
	plugindir = getDirectory("plugins");
	path = plugindir + "Scripts\\Image\\Hyperstacks\\Temporal-Color_Code.ijm";
	TCC_code = File.openAsString(path);
	
	oldline = "lutA = makeLUTsArray";
	newline = "lutA = getList(\"LUTs\"); //makeLUTsArray";
	newTCC = TCC_code.replace(oldline,newline);
	
	File.saveString(newTCC, path);
}
```

**Pull request merged**
